---

- name: Stop Nginx
  service: name=nginx state=stopped

- name: Obtain or renew cert for domain
  shell: executable=/bin/bash cd /opt/certbot && ./certbot-auto certonly -m {{ letsencrypt_email }} --domains {{ letsencrypt_domain }},www.{{ letsencrypt_domain }} --agree-tos --renew-by-default --standalone --expand

- name: Start Nginx
  service: name=nginx state=started
